version: 2

before:
  hooks:
  - go mod download

builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  main: ./cmd/travelgrunt/main.go
  ldflags:
  - -X main.appVersion={{.Env.RELEASE_VERSION}}
  tags:
  - netgo
  - osusergo

brews:
- name: travelgrunt
  homepage: 'https://github.com/ivanilves/travelgrunt'
  description: 'cd inside [mono]repos without fatigue!'
  directory: Formula
  repository:
    owner: ivanilves
    name: homebrew-tap

archives:
- name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
  format: tar.gz

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-snapshot"

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
    - '^chore'
    - '^test'
    - '^style'
    - '^docs'
    - '^Merge pull request'
